import React from "react";
import useCheckMobileScreen from "../hooks/useCheckMobileScreen.ts";
import Head from "next/head";
import Navigation from "../components/Navigation/navigation.component";
import Footer from "../components/Footer/footer.component";
import Image from "next/image";
const Layout = ({ children }) => {
  const isMobile = useCheckMobileScreen(800);

  return (
    <div className="bg-[#DFD8D7]">
      {isMobile ? (
        <main>
          <Head>
            <title>podobro Kasia Podraza</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navigation isMobile={isMobile} />
          {children}
          <Footer />
        </main>
      ) : (
        <div class="flex items-center justify-center h-screen bg-gray-200">
          <div class="container">
            <div class="bg-white rounded-lg shadow-lg p-5 md:p-20 mx-2">
              <div class="text-center">
                <h2 class="text-4xl tracking-tight leading-10 font-extrabold text-gray-900 sm:text-5xl sm:leading-none md:text-6xl">
                  <Image
                    src="/images/logo-podobro-pl.png"
                    alt="logo"
                    width={isMobile ? "113" : "187"}
                    height={isMobile ? "83" : "137"}
                  />
                </h2>
                <h3 class="text-xl md:text-5xl mt-10">Strona w budowie</h3>
                <p class="text-md md:text-2xl mt-10">
                  Strona aktualnie dostępna jest wyłącznie w wersji mobilnej.
                </p>
              </div>
              <div class="flex flex-wrap mt-10 justify-center">
                <div class="m-3">
                  <a
                    href="https://www.facebook.com/katarzyna.stefanska1"
                    title="Quicktoolz On Facebook"
                    class="md:w-32 bg-white tracking-wide text-gray-800 font-bold rounded border-2 border-blue-600 hover:border-blue-600 hover:bg-blue-600 hover:text-white shadow-md py-2 px-6 inline-flex items-center"
                  >
                    <span class="mx-auto">Facebook</span>
                  </a>
                </div>
                <div class="m-3">
                  <a
                    href="https://www.instagram.com/kasiapodraza/"
                    title="Quicktoolz On Twitter"
                    class="md:w-32 bg-white tracking-wide text-gray-800 font-bold rounded border-2 border-[#E1306C] hover:border-[#E1306C] hover:bg-[#E1306C] hover:text-white shadow-md py-2 px-6 inline-flex items-center"
                  >
                    <span class="mx-auto">Instagram</span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Layout;
