import React from "react";
import useCheckMobileScreen from "../hooks/useCheckMobileScreen.ts";
import Head from "next/head";
import Navigation from "../components/Navigation/navigation.component";
import Footer from "../components/Footer/footer.component";

const Layout = ({ children }) => {
  const isMobile = useCheckMobileScreen(800);

  return (
    <div className="bg-[#DFD8D7]">
      <main>
        <Head>
          <title>podobro Kasia Podraza</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navigation isMobile={isMobile} />
        {children}
        <Footer />
      </main>
    </div>
  );
};

export default Layout;
